stages:
  - deploy-frontend
  - deploy-backend

deploy-prod:
  stage: deploy-frontend
  script:
    - git config --global user.email "leon.kranjcevic@fer.hr";
      git config --global user.name "leon.kranjcevic@fer.hr";
      cd ./inverzni-inzenjeri-ui;
      git init;
      git add .;
      git commit -m "heroku deploy";
      git push -f https://$HEROKU_USER:10457204-9a01-48dc-aaf9-a2c52a10dbef@git.heroku.com/$HEROKU_APP_STAGING_2.git HEAD:master
  only:
    - development
  allow_failure: true
deploy2-prod:
  stage: deploy-backend
  script:
    - cd ./inverzni-inzenjeri-api
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING_1 --api-key=10457204-9a01-48dc-aaf9-a2c52a10dbef
  only:
    - development
  allow_failure: true


