export enum MessageRole {
    FRIEND_REQUEST = "FRIEND_REQUEST",
    ACCEPTED_FRIEND_REQUEST = "ACCEPTED_FRIEND_REQUEST",
    BADGE_UPDATE = "BADGE_UPDATE",
    ADMIN_HIKER_ON_CALL_REQUEST = "ADMIN_HIKER_ON_CALL_REQUEST",
    HIKER_ON_CALL_RESPONSE = "HIKER_ON_CALL_RESPONSE",
    EVENT_REQUEST = "EVENT_REQUEST"
}